trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest' 

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration\iaac\azure\kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmResourceGroupName: 'cloud-shell-storage-centralindia'
    backendAzureRmStorageAccountName: 'banesingh_storage'
    backendAzureRmContainerName: 'banesinghstoragecontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'